package cn.fighter3.entity;

import java.util.Date;

public class OrmUserJpa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.id
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.name
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.password
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.salt
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.email
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.phone_number
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.status
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.create_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.last_login_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user_jpa.last_update_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.id
     *
     * @return the value of orm_user_jpa.id
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.id
     *
     * @param id the value for orm_user_jpa.id
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.name
     *
     * @return the value of orm_user_jpa.name
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.name
     *
     * @param name the value for orm_user_jpa.name
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.password
     *
     * @return the value of orm_user_jpa.password
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.password
     *
     * @param password the value for orm_user_jpa.password
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.salt
     *
     * @return the value of orm_user_jpa.salt
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.salt
     *
     * @param salt the value for orm_user_jpa.salt
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.email
     *
     * @return the value of orm_user_jpa.email
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.email
     *
     * @param email the value for orm_user_jpa.email
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.phone_number
     *
     * @return the value of orm_user_jpa.phone_number
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.phone_number
     *
     * @param phoneNumber the value for orm_user_jpa.phone_number
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.status
     *
     * @return the value of orm_user_jpa.status
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.status
     *
     * @param status the value for orm_user_jpa.status
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.create_time
     *
     * @return the value of orm_user_jpa.create_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.create_time
     *
     * @param createTime the value for orm_user_jpa.create_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.last_login_time
     *
     * @return the value of orm_user_jpa.last_login_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.last_login_time
     *
     * @param lastLoginTime the value for orm_user_jpa.last_login_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user_jpa.last_update_time
     *
     * @return the value of orm_user_jpa.last_update_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user_jpa.last_update_time
     *
     * @param lastUpdateTime the value for orm_user_jpa.last_update_time
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}