package cn.fighter3.dao;

import cn.fighter3.entity.OrmUserJpa;
import cn.fighter3.entity.OrmUserJpaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrmUserJpaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    long countByExample(OrmUserJpaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    int deleteByExample(OrmUserJpaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    int insert(OrmUserJpa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    int insertSelective(OrmUserJpa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    List<OrmUserJpa> selectByExample(OrmUserJpaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    OrmUserJpa selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    int updateByExampleSelective(@Param("record") OrmUserJpa record, @Param("example") OrmUserJpaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    int updateByExample(@Param("record") OrmUserJpa record, @Param("example") OrmUserJpaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    int updateByPrimaryKeySelective(OrmUserJpa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user_jpa
     *
     * @mbg.generated Wed Aug 24 16:31:08 CST 2022
     */
    int updateByPrimaryKey(OrmUserJpa record);
}